//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBS_PER_ALL_PEOPLE_F
    {
        public int PERSON_ID { get; set; }
        public System.DateTime EFFECTIVE_START_DATE { get; set; }
        public System.DateTime EFFECTIVE_END_DATE { get; set; }
        public long BUSINESS_GROUP_ID { get; set; }
        public long PERSON_TYPE_ID { get; set; }
        public string LAST_NAME { get; set; }
        public System.DateTime START_DATE { get; set; }
        public string APPLICANT_NUMBER { get; set; }
        public string BACKGROUND_CHECK_STATUS { get; set; }
        public Nullable<System.DateTime> BACKGROUND_DATE_CHECK { get; set; }
        public string BLOOD_TYPE { get; set; }
        public Nullable<long> COMMENT_ID { get; set; }
        public string CORRESPONDENCE_LANGUAGE { get; set; }
        public string CURRENT_APPLICANT_FLAG { get; set; }
        public string CURRENT_EMP_OR_APL_FLAG { get; set; }
        public string CURRENT_EMPLOYEE_FLAG { get; set; }
        public Nullable<System.DateTime> DATE_EMPLOYEE_DATA_VERIFIED { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string EMPLOYEE_NUMBER { get; set; }
        public string EXPENSE_CHECK_SEND_TO_ADDRESS { get; set; }
        public string FAST_PATH_EMPLOYEE { get; set; }
        public string FIRST_NAME { get; set; }
        public Nullable<decimal> FTE_CAPACITY { get; set; }
        public string FULL_NAME { get; set; }
        public Nullable<System.DateTime> HOLD_APPLICANT_DATE_UNTIL { get; set; }
        public string HONORS { get; set; }
        public string INTERNAL_LOCATION { get; set; }
        public string KNOWN_AS { get; set; }
        public string LAST_MEDICAL_TEST_BY { get; set; }
        public Nullable<System.DateTime> LAST_MEDICAL_TEST_DATE { get; set; }
        public string MAILSTOP { get; set; }
        public string MARITAL_STATUS { get; set; }
        public string MIDDLE_NAMES { get; set; }
        public string NATIONALITY { get; set; }
        public string NATIONAL_IDENTIFIER { get; set; }
        public string OFFICE_NUMBER { get; set; }
        public string ON_MILITARY_SERVICE { get; set; }
        public string ORDER_NAME { get; set; }
        public string PRE_NAME_ADJUNCT { get; set; }
        public string PREVIOUS_LAST_NAME { get; set; }
        public Nullable<System.DateTime> PROJECTED_START_DATE { get; set; }
        public string REHIRE_AUTHORIZOR { get; set; }
        public string REHIRE_REASON { get; set; }
        public string REHIRE_RECOMMENDATION { get; set; }
        public string RESUME_EXISTS { get; set; }
        public Nullable<System.DateTime> RESUME_LAST_UPDATED { get; set; }
        public string REGISTERED_DISABLED_FLAG { get; set; }
        public string SECOND_PASSPORT_EXISTS { get; set; }
        public string SEX { get; set; }
        public string STUDENT_STATUS { get; set; }
        public string SUFFIX { get; set; }
        public string TITLE { get; set; }
        public Nullable<long> VENDOR_ID { get; set; }
        public string WORK_SCHEDULE { get; set; }
        public string WORK_TELEPHONE { get; set; }
        public string COORD_BEN_MED_PLN_NO { get; set; }
        public string COORD_BEN_NO_CVG_FLAG { get; set; }
        public Nullable<System.DateTime> DPDNT_ADOPTION_DATE { get; set; }
        public string DPDNT_VLNTRY_SVCE_FLAG { get; set; }
        public Nullable<System.DateTime> RECEIPT_OF_DEATH_CERT_DATE { get; set; }
        public string USES_TOBACCO_FLAG { get; set; }
        public Nullable<long> BENEFIT_GROUP_ID { get; set; }
        public Nullable<long> REQUEST_ID { get; set; }
        public Nullable<long> PROGRAM_APPLICATION_ID { get; set; }
        public Nullable<long> PROGRAM_ID { get; set; }
        public Nullable<System.DateTime> PROGRAM_UPDATE_DATE { get; set; }
        public string ATTRIBUTE_CATEGORY { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string ATTRIBUTE9 { get; set; }
        public string ATTRIBUTE10 { get; set; }
        public string ATTRIBUTE11 { get; set; }
        public string ATTRIBUTE12 { get; set; }
        public string ATTRIBUTE13 { get; set; }
        public string ATTRIBUTE14 { get; set; }
        public string ATTRIBUTE15 { get; set; }
        public string ATTRIBUTE16 { get; set; }
        public string ATTRIBUTE17 { get; set; }
        public string ATTRIBUTE18 { get; set; }
        public string ATTRIBUTE19 { get; set; }
        public string ATTRIBUTE20 { get; set; }
        public string ATTRIBUTE21 { get; set; }
        public string ATTRIBUTE22 { get; set; }
        public string ATTRIBUTE23 { get; set; }
        public string ATTRIBUTE24 { get; set; }
        public string ATTRIBUTE25 { get; set; }
        public string ATTRIBUTE26 { get; set; }
        public string ATTRIBUTE27 { get; set; }
        public string ATTRIBUTE28 { get; set; }
        public string ATTRIBUTE29 { get; set; }
        public string ATTRIBUTE30 { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<long> LAST_UPDATED_BY { get; set; }
        public Nullable<long> LAST_UPDATE_LOGIN { get; set; }
        public Nullable<long> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string PER_INFORMATION_CATEGORY { get; set; }
        public string PER_INFORMATION1 { get; set; }
        public string PER_INFORMATION2 { get; set; }
        public string PER_INFORMATION3 { get; set; }
        public string PER_INFORMATION4 { get; set; }
        public string PER_INFORMATION5 { get; set; }
        public string PER_INFORMATION6 { get; set; }
        public string PER_INFORMATION7 { get; set; }
        public string PER_INFORMATION8 { get; set; }
        public string PER_INFORMATION9 { get; set; }
        public string PER_INFORMATION10 { get; set; }
        public string PER_INFORMATION11 { get; set; }
        public string PER_INFORMATION12 { get; set; }
        public string PER_INFORMATION13 { get; set; }
        public string PER_INFORMATION14 { get; set; }
        public string PER_INFORMATION15 { get; set; }
        public string PER_INFORMATION16 { get; set; }
        public string PER_INFORMATION17 { get; set; }
        public string PER_INFORMATION18 { get; set; }
        public string PER_INFORMATION19 { get; set; }
        public string PER_INFORMATION20 { get; set; }
        public string PER_INFORMATION21 { get; set; }
        public string PER_INFORMATION22 { get; set; }
        public string PER_INFORMATION23 { get; set; }
        public string PER_INFORMATION24 { get; set; }
        public string PER_INFORMATION25 { get; set; }
        public string PER_INFORMATION26 { get; set; }
        public string PER_INFORMATION27 { get; set; }
        public string PER_INFORMATION28 { get; set; }
        public string PER_INFORMATION29 { get; set; }
        public string PER_INFORMATION30 { get; set; }
        public Nullable<int> OBJECT_VERSION_NUMBER { get; set; }
        public Nullable<System.DateTime> DATE_OF_DEATH { get; set; }
        public Nullable<System.DateTime> ORIGINAL_DATE_OF_HIRE { get; set; }
        public string TOWN_OF_BIRTH { get; set; }
        public string REGION_OF_BIRTH { get; set; }
        public string COUNTRY_OF_BIRTH { get; set; }
        public string GLOBAL_PERSON_ID { get; set; }
        public string COORD_BEN_MED_PL_NAME { get; set; }
        public string COORD_BEN_MED_INSR_CRR_NAME { get; set; }
        public string COORD_BEN_MED_INSR_CRR_IDENT { get; set; }
        public string COORD_BEN_MED_EXT_ER { get; set; }
        public Nullable<System.DateTime> COORD_BEN_MED_CVG_STRT_DT { get; set; }
        public Nullable<System.DateTime> COORD_BEN_MED_CVG_END_DT { get; set; }
        public Nullable<long> PARTY_ID { get; set; }
        public string NPW_NUMBER { get; set; }
        public string CURRENT_NPW_FLAG { get; set; }
        public string GLOBAL_NAME { get; set; }
        public string LOCAL_NAME { get; set; }
    }
}
