//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBS_FND_USER
    {
        public long USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public long LAST_UPDATED_BY { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public long CREATED_BY { get; set; }
        public Nullable<long> LAST_UPDATE_LOGIN { get; set; }
        public string ENCRYPTED_FOUNDATION_PASSWORD { get; set; }
        public string ENCRYPTED_USER_PASSWORD { get; set; }
        public decimal SESSION_NUMBER { get; set; }
        public System.DateTime START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> LAST_LOGON_DATE { get; set; }
        public Nullable<System.DateTime> PASSWORD_DATE { get; set; }
        public Nullable<long> PASSWORD_ACCESSES_LEFT { get; set; }
        public Nullable<long> PASSWORD_LIFESPAN_ACCESSES { get; set; }
        public Nullable<long> PASSWORD_LIFESPAN_DAYS { get; set; }
        public Nullable<long> EMPLOYEE_ID { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string FAX { get; set; }
        public Nullable<long> CUSTOMER_ID { get; set; }
        public Nullable<long> SUPPLIER_ID { get; set; }
        public string WEB_PASSWORD { get; set; }
        public Nullable<System.Guid> USER_GUID { get; set; }
        public Nullable<long> GCN_CODE_COMBINATION_ID { get; set; }
        public Nullable<decimal> PERSON_PARTY_ID { get; set; }
    }
}
