//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBS_MTL_TRANSACTION_TYPES
    {
        public decimal TRANSACTION_TYPE_ID { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public decimal LAST_UPDATED_BY { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public decimal CREATED_BY { get; set; }
        public string TRANSACTION_TYPE_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal TRANSACTION_ACTION_ID { get; set; }
        public decimal TRANSACTION_SOURCE_TYPE_ID { get; set; }
        public string SHORTAGE_MSG_BACKGROUND_FLAG { get; set; }
        public string SHORTAGE_MSG_ONLINE_FLAG { get; set; }
        public Nullable<System.DateTime> DISABLE_DATE { get; set; }
        public string USER_DEFINED_FLAG { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string ATTRIBUTE9 { get; set; }
        public string ATTRIBUTE10 { get; set; }
        public string ATTRIBUTE11 { get; set; }
        public string ATTRIBUTE12 { get; set; }
        public string ATTRIBUTE13 { get; set; }
        public string ATTRIBUTE14 { get; set; }
        public string ATTRIBUTE15 { get; set; }
        public string ATTRIBUTE_CATEGORY { get; set; }
        public Nullable<decimal> TYPE_CLASS { get; set; }
        public Nullable<decimal> STATUS_CONTROL_FLAG { get; set; }
        public string LOCATION_REQUIRED_FLAG { get; set; }
    }
}
