//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBS_PO_AGENTS
    {
        public int AGENT_ID { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public decimal LAST_UPDATED_BY { get; set; }
        public Nullable<decimal> LAST_UPDATE_LOGIN { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public Nullable<decimal> LOCATION_ID { get; set; }
        public Nullable<decimal> CATEGORY_ID { get; set; }
        public Nullable<decimal> AUTHORIZATION_LIMIT { get; set; }
        public Nullable<System.DateTime> START_DATE_ACTIVE { get; set; }
        public Nullable<System.DateTime> END_DATE_ACTIVE { get; set; }
        public string ATTRIBUTE_CATEGORY { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string ATTRIBUTE9 { get; set; }
        public string ATTRIBUTE10 { get; set; }
        public string ATTRIBUTE11 { get; set; }
        public string ATTRIBUTE12 { get; set; }
        public string ATTRIBUTE13 { get; set; }
        public string ATTRIBUTE14 { get; set; }
        public string ATTRIBUTE15 { get; set; }
        public Nullable<decimal> REQUEST_ID { get; set; }
        public Nullable<decimal> PROGRAM_APPLICATION_ID { get; set; }
        public Nullable<decimal> PROGRAM_ID { get; set; }
        public Nullable<System.DateTime> PROGRAM_UPDATE_DATE { get; set; }
    }
}
