//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WMSEntities : DbContext
    {
        public WMSEntities()
            : base("name=WMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EBS_FND_USER> EBS_FND_USER { get; set; }
        public virtual DbSet<EBS_MTL_ITEM_LOCATIONS> EBS_MTL_ITEM_LOCATIONS { get; set; }
        public virtual DbSet<EBS_MTL_SECONDARY_INVENTORIES> EBS_MTL_SECONDARY_INVENTORIES { get; set; }
        public virtual DbSet<EBS_MTL_SYSTEM_ITEMS_B> EBS_MTL_SYSTEM_ITEMS_B { get; set; }
        public virtual DbSet<EBS_MTL_TRANSACTION_TYPES> EBS_MTL_TRANSACTION_TYPES { get; set; }
        public virtual DbSet<EBS_MTL_TXN_REQUEST_HEADERS> EBS_MTL_TXN_REQUEST_HEADERS { get; set; }
        public virtual DbSet<EBS_MTL_TXN_REQUEST_LINES> EBS_MTL_TXN_REQUEST_LINES { get; set; }
        public virtual DbSet<EBS_MTL_TXN_SOURCE_TYPES> EBS_MTL_TXN_SOURCE_TYPES { get; set; }
        public virtual DbSet<EBS_MTL_UNITS_OF_MEASURE_TL> EBS_MTL_UNITS_OF_MEASURE_TL { get; set; }
        public virtual DbSet<EBS_PER_ALL_PEOPLE_F> EBS_PER_ALL_PEOPLE_F { get; set; }
        public virtual DbSet<EBS_PO_AGENTS> EBS_PO_AGENTS { get; set; }
        public virtual DbSet<EBS_USE_DEPT> EBS_USE_DEPT { get; set; }
        public virtual DbSet<WMS_AD_USERS> WMS_AD_USERS { get; set; }
        public virtual DbSet<WMS_CUSTOMER> WMS_CUSTOMER { get; set; }
        public virtual DbSet<WMS_DEPT> WMS_DEPT { get; set; }
        public virtual DbSet<WMS_ERP_USERS> WMS_ERP_USERS { get; set; }
        public virtual DbSet<WMS_FUNCTIONS> WMS_FUNCTIONS { get; set; }
        public virtual DbSet<WMS_INVENTORY> WMS_INVENTORY { get; set; }
        public virtual DbSet<WMS_ITEMS> WMS_ITEMS { get; set; }
        public virtual DbSet<WMS_LOCATOR> WMS_LOCATOR { get; set; }
        public virtual DbSet<WMS_MENU> WMS_MENU { get; set; }
        public virtual DbSet<WMS_ONHANDETAIL> WMS_ONHANDETAIL { get; set; }
        public virtual DbSet<WMS_ORG> WMS_ORG { get; set; }
        public virtual DbSet<WMS_OU> WMS_OU { get; set; }
        public virtual DbSet<WMS_POAGENT> WMS_POAGENT { get; set; }
        public virtual DbSet<WMS_ROLEFUNCTION> WMS_ROLEFUNCTION { get; set; }
        public virtual DbSet<WMS_ROLES> WMS_ROLES { get; set; }
        public virtual DbSet<WMS_SALESREP> WMS_SALESREP { get; set; }
        public virtual DbSet<WMS_TRANSACTIONS> WMS_TRANSACTIONS { get; set; }
        public virtual DbSet<WMS_TRANSACTIONTYPE> WMS_TRANSACTIONTYPE { get; set; }
        public virtual DbSet<WMS_TYPE> WMS_TYPE { get; set; }
        public virtual DbSet<WMS_UOM> WMS_UOM { get; set; }
        public virtual DbSet<WMS_USERORG> WMS_USERORG { get; set; }
        public virtual DbSet<WMS_USERROLES> WMS_USERROLES { get; set; }
        public virtual DbSet<WMS_USERS> WMS_USERS { get; set; }
        public virtual DbSet<WMS_VENDOR> WMS_VENDOR { get; set; }
    }
}
