//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_USERS
    {
        public decimal USER_ID { get; set; }
        public Nullable<decimal> TO_USERID { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<decimal> ERP_ID { get; set; }
        public Nullable<decimal> AD_ID { get; set; }
        public Nullable<decimal> OU_ID { get; set; }
        public Nullable<decimal> DEPT_ID { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
    }
}
