//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_TRANSACTIONS
    {
        public decimal T_ID { get; set; }
        public decimal TYPE_ID { get; set; }
        public decimal OU_ID { get; set; }
        public decimal ORG_ID { get; set; }
        public decimal INV_ID { get; set; }
        public Nullable<decimal> LOC_ID { get; set; }
        public Nullable<decimal> AGT_ID { get; set; }
        public Nullable<decimal> DEPT_ID { get; set; }
        public decimal ITEM_ID { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<decimal> UOM_ID { get; set; }
        public Nullable<decimal> QTY2 { get; set; }
        public Nullable<decimal> UOM_ID2 { get; set; }
        public string LOT_NUMBER { get; set; }
        public string HEAT_NUMBER { get; set; }
        public Nullable<System.DateTime> INV_DATE { get; set; }
        public Nullable<decimal> VND_ID { get; set; }
        public Nullable<decimal> SOURCE_TYPE { get; set; }
        public Nullable<decimal> SOURCE_ID { get; set; }
        public string SOURCE_CODE { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<decimal> FLAG { get; set; }
    }
}
