//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.WCFModel
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class EBS_USE_DEPT
    {
    	[DataMember]
        public int DEPT_VALUE_SET_ID { get; set; }
    	[DataMember]
        public long DEPT_VALUE_ID { get; set; }
    	[DataMember]
        public string DEPT_VALUE { get; set; }
    	[DataMember]
        public string DESCRIPTION { get; set; }
    	[DataMember]
        public string FLEX_VALUE_MEANING { get; set; }
    	[DataMember]
        public System.DateTime LAST_UPDATE_DATE { get; set; }
    	[DataMember]
        public long LAST_UPDATED_BY { get; set; }
    	[DataMember]
        public System.DateTime CREATION_DATE { get; set; }
    	[DataMember]
        public long CREATED_BY { get; set; }
    	[DataMember]
        public Nullable<long> LAST_UPDATE_LOGIN { get; set; }
    	[DataMember]
        public string ENABLED_FLAG { get; set; }
    	[DataMember]
        public string SUMMARY_FLAG { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> START_DATE_ACTIVE { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> END_DATE_ACTIVE { get; set; }
    	[DataMember]
        public string PARENT_FLEX_VALUE_LOW { get; set; }
    	[DataMember]
        public string PARENT_FLEX_VALUE_HIGH { get; set; }
    	[DataMember]
        public Nullable<long> STRUCTURED_HIERARCHY_LEVEL { get; set; }
    	[DataMember]
        public string HIERARCHY_LEVEL { get; set; }
    	[DataMember]
        public string COMPILED_VALUE_ATTRIBUTES { get; set; }
    	[DataMember]
        public string VALUE_CATEGORY { get; set; }
    	[DataMember]
        public string ATTRIBUTE1 { get; set; }
    	[DataMember]
        public string ATTRIBUTE2 { get; set; }
    	[DataMember]
        public string ATTRIBUTE3 { get; set; }
    	[DataMember]
        public string ATTRIBUTE4 { get; set; }
    	[DataMember]
        public string ATTRIBUTE5 { get; set; }
    	[DataMember]
        public string ATTRIBUTE6 { get; set; }
    	[DataMember]
        public string ATTRIBUTE7 { get; set; }
    	[DataMember]
        public string ATTRIBUTE8 { get; set; }
    	[DataMember]
        public string ATTRIBUTE9 { get; set; }
    	[DataMember]
        public string ATTRIBUTE10 { get; set; }
    	[DataMember]
        public string ATTRIBUTE11 { get; set; }
    	[DataMember]
        public string ATTRIBUTE12 { get; set; }
    	[DataMember]
        public string ATTRIBUTE13 { get; set; }
    	[DataMember]
        public string ATTRIBUTE14 { get; set; }
    	[DataMember]
        public string ATTRIBUTE15 { get; set; }
    	[DataMember]
        public string ATTRIBUTE16 { get; set; }
    	[DataMember]
        public string ATTRIBUTE17 { get; set; }
    	[DataMember]
        public string ATTRIBUTE18 { get; set; }
    	[DataMember]
        public string ATTRIBUTE19 { get; set; }
    	[DataMember]
        public string ATTRIBUTE20 { get; set; }
    	[DataMember]
        public string ATTRIBUTE21 { get; set; }
    	[DataMember]
        public string ATTRIBUTE22 { get; set; }
    	[DataMember]
        public string ATTRIBUTE23 { get; set; }
    	[DataMember]
        public string ATTRIBUTE24 { get; set; }
    	[DataMember]
        public string ATTRIBUTE25 { get; set; }
    	[DataMember]
        public string ATTRIBUTE26 { get; set; }
    	[DataMember]
        public string ATTRIBUTE27 { get; set; }
    	[DataMember]
        public string ATTRIBUTE28 { get; set; }
    	[DataMember]
        public string ATTRIBUTE29 { get; set; }
    	[DataMember]
        public string ATTRIBUTE30 { get; set; }
    	[DataMember]
        public string ATTRIBUTE31 { get; set; }
    	[DataMember]
        public string ATTRIBUTE32 { get; set; }
    	[DataMember]
        public string ATTRIBUTE33 { get; set; }
    	[DataMember]
        public string ATTRIBUTE34 { get; set; }
    	[DataMember]
        public string ATTRIBUTE35 { get; set; }
    	[DataMember]
        public string ATTRIBUTE36 { get; set; }
    	[DataMember]
        public string ATTRIBUTE37 { get; set; }
    	[DataMember]
        public string ATTRIBUTE38 { get; set; }
    	[DataMember]
        public string ATTRIBUTE39 { get; set; }
    	[DataMember]
        public string ATTRIBUTE40 { get; set; }
    	[DataMember]
        public string ATTRIBUTE41 { get; set; }
    	[DataMember]
        public string ATTRIBUTE42 { get; set; }
    	[DataMember]
        public string ATTRIBUTE43 { get; set; }
    	[DataMember]
        public string ATTRIBUTE44 { get; set; }
    	[DataMember]
        public string ATTRIBUTE45 { get; set; }
    	[DataMember]
        public string ATTRIBUTE46 { get; set; }
    	[DataMember]
        public string ATTRIBUTE47 { get; set; }
    	[DataMember]
        public string ATTRIBUTE48 { get; set; }
    	[DataMember]
        public string ATTRIBUTE49 { get; set; }
    	[DataMember]
        public string ATTRIBUTE50 { get; set; }
    	[DataMember]
        public Nullable<long> ATTRIBUTE_SORT_ORDER { get; set; }
    }
}
