//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.WCFModel
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class EBS_MTL_ITEM_LOCATIONS
    {
    	[DataMember]
        public decimal INVENTORY_LOCATION_ID { get; set; }
    	[DataMember]
        public decimal ORGANIZATION_ID { get; set; }
    	[DataMember]
        public System.DateTime LAST_UPDATE_DATE { get; set; }
    	[DataMember]
        public decimal LAST_UPDATED_BY { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
    	[DataMember]
        public Nullable<decimal> CREATED_BY { get; set; }
    	[DataMember]
        public Nullable<decimal> LAST_UPDATE_LOGIN { get; set; }
    	[DataMember]
        public string DESCRIPTION { get; set; }
    	[DataMember]
        public string DESCRIPTIVE_TEXT { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> DISABLE_DATE { get; set; }
    	[DataMember]
        public Nullable<decimal> INVENTORY_LOCATION_TYPE { get; set; }
    	[DataMember]
        public Nullable<decimal> PICKING_ORDER { get; set; }
    	[DataMember]
        public string PHYSICAL_LOCATION_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> LOCATION_MAXIMUM_UNITS { get; set; }
    	[DataMember]
        public string SUBINVENTORY_CODE { get; set; }
    	[DataMember]
        public string LOCATION_WEIGHT_UOM_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> MAX_WEIGHT { get; set; }
    	[DataMember]
        public string VOLUME_UOM_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> MAX_CUBIC_AREA { get; set; }
    	[DataMember]
        public Nullable<decimal> X_COORDINATE { get; set; }
    	[DataMember]
        public Nullable<decimal> Y_COORDINATE { get; set; }
    	[DataMember]
        public Nullable<decimal> Z_COORDINATE { get; set; }
    	[DataMember]
        public Nullable<decimal> INVENTORY_ACCOUNT_ID { get; set; }
    	[DataMember]
        public string SEGMENT1 { get; set; }
    	[DataMember]
        public string SEGMENT2 { get; set; }
    	[DataMember]
        public string SEGMENT3 { get; set; }
    	[DataMember]
        public string SEGMENT4 { get; set; }
    	[DataMember]
        public string SEGMENT5 { get; set; }
    	[DataMember]
        public string SEGMENT6 { get; set; }
    	[DataMember]
        public string SEGMENT7 { get; set; }
    	[DataMember]
        public string SEGMENT8 { get; set; }
    	[DataMember]
        public string SEGMENT9 { get; set; }
    	[DataMember]
        public string SEGMENT10 { get; set; }
    	[DataMember]
        public string SEGMENT11 { get; set; }
    	[DataMember]
        public string SEGMENT12 { get; set; }
    	[DataMember]
        public string SEGMENT13 { get; set; }
    	[DataMember]
        public string SEGMENT14 { get; set; }
    	[DataMember]
        public string SEGMENT15 { get; set; }
    	[DataMember]
        public string SEGMENT16 { get; set; }
    	[DataMember]
        public string SEGMENT17 { get; set; }
    	[DataMember]
        public string SEGMENT18 { get; set; }
    	[DataMember]
        public string SEGMENT19 { get; set; }
    	[DataMember]
        public string SEGMENT20 { get; set; }
    	[DataMember]
        public string SUMMARY_FLAG { get; set; }
    	[DataMember]
        public string ENABLED_FLAG { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> START_DATE_ACTIVE { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> END_DATE_ACTIVE { get; set; }
    	[DataMember]
        public string ATTRIBUTE_CATEGORY { get; set; }
    	[DataMember]
        public string ATTRIBUTE1 { get; set; }
    	[DataMember]
        public string ATTRIBUTE2 { get; set; }
    	[DataMember]
        public string ATTRIBUTE3 { get; set; }
    	[DataMember]
        public string ATTRIBUTE4 { get; set; }
    	[DataMember]
        public string ATTRIBUTE5 { get; set; }
    	[DataMember]
        public string ATTRIBUTE6 { get; set; }
    	[DataMember]
        public string ATTRIBUTE7 { get; set; }
    	[DataMember]
        public string ATTRIBUTE8 { get; set; }
    	[DataMember]
        public string ATTRIBUTE9 { get; set; }
    	[DataMember]
        public string ATTRIBUTE10 { get; set; }
    	[DataMember]
        public string ATTRIBUTE11 { get; set; }
    	[DataMember]
        public string ATTRIBUTE12 { get; set; }
    	[DataMember]
        public string ATTRIBUTE13 { get; set; }
    	[DataMember]
        public string ATTRIBUTE14 { get; set; }
    	[DataMember]
        public string ATTRIBUTE15 { get; set; }
    	[DataMember]
        public Nullable<decimal> REQUEST_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> PROGRAM_APPLICATION_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> PROGRAM_ID { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> PROGRAM_UPDATE_DATE { get; set; }
    	[DataMember]
        public Nullable<long> PROJECT_ID { get; set; }
    	[DataMember]
        public Nullable<long> TASK_ID { get; set; }
    	[DataMember]
        public Nullable<long> PHYSICAL_LOCATION_ID { get; set; }
    	[DataMember]
        public string PICK_UOM_CODE { get; set; }
    	[DataMember]
        public string DIMENSION_UOM_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> LENGTH { get; set; }
    	[DataMember]
        public Nullable<decimal> WIDTH { get; set; }
    	[DataMember]
        public Nullable<decimal> HEIGHT { get; set; }
    	[DataMember]
        public Nullable<decimal> LOCATOR_STATUS { get; set; }
    	[DataMember]
        public Nullable<decimal> STATUS_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> CURRENT_CUBIC_AREA { get; set; }
    	[DataMember]
        public Nullable<decimal> AVAILABLE_CUBIC_AREA { get; set; }
    	[DataMember]
        public Nullable<decimal> CURRENT_WEIGHT { get; set; }
    	[DataMember]
        public Nullable<decimal> AVAILABLE_WEIGHT { get; set; }
    	[DataMember]
        public Nullable<decimal> LOCATION_CURRENT_UNITS { get; set; }
    	[DataMember]
        public Nullable<decimal> LOCATION_AVAILABLE_UNITS { get; set; }
    	[DataMember]
        public Nullable<decimal> INVENTORY_ITEM_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> SUGGESTED_CUBIC_AREA { get; set; }
    	[DataMember]
        public Nullable<decimal> SUGGESTED_WEIGHT { get; set; }
    	[DataMember]
        public Nullable<decimal> LOCATION_SUGGESTED_UNITS { get; set; }
    	[DataMember]
        public string EMPTY_FLAG { get; set; }
    	[DataMember]
        public string MIXED_ITEMS_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> DROPPING_ORDER { get; set; }
    	[DataMember]
        public Nullable<decimal> AVAILABILITY_TYPE { get; set; }
    	[DataMember]
        public Nullable<decimal> INVENTORY_ATP_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> RESERVABLE_TYPE { get; set; }
    	[DataMember]
        public string ALIAS { get; set; }
    }
}
