//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.WCFModel
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class EBS_MTL_SECONDARY_INVENTORIES
    {
    	[DataMember]
        public string SECONDARY_INVENTORY_NAME { get; set; }
    	[DataMember]
        public decimal ORGANIZATION_ID { get; set; }
    	[DataMember]
        public System.DateTime LAST_UPDATE_DATE { get; set; }
    	[DataMember]
        public decimal LAST_UPDATED_BY { get; set; }
    	[DataMember]
        public System.DateTime CREATION_DATE { get; set; }
    	[DataMember]
        public decimal CREATED_BY { get; set; }
    	[DataMember]
        public Nullable<decimal> LAST_UPDATE_LOGIN { get; set; }
    	[DataMember]
        public string DESCRIPTION { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> DISABLE_DATE { get; set; }
    	[DataMember]
        public decimal INVENTORY_ATP_CODE { get; set; }
    	[DataMember]
        public decimal AVAILABILITY_TYPE { get; set; }
    	[DataMember]
        public decimal RESERVABLE_TYPE { get; set; }
    	[DataMember]
        public Nullable<decimal> LOCATOR_TYPE { get; set; }
    	[DataMember]
        public Nullable<decimal> PICKING_ORDER { get; set; }
    	[DataMember]
        public Nullable<decimal> MATERIAL_ACCOUNT { get; set; }
    	[DataMember]
        public Nullable<decimal> MATERIAL_OVERHEAD_ACCOUNT { get; set; }
    	[DataMember]
        public Nullable<decimal> RESOURCE_ACCOUNT { get; set; }
    	[DataMember]
        public Nullable<decimal> OVERHEAD_ACCOUNT { get; set; }
    	[DataMember]
        public Nullable<decimal> OUTSIDE_PROCESSING_ACCOUNT { get; set; }
    	[DataMember]
        public decimal QUANTITY_TRACKED { get; set; }
    	[DataMember]
        public decimal ASSET_INVENTORY { get; set; }
    	[DataMember]
        public Nullable<decimal> SOURCE_TYPE { get; set; }
    	[DataMember]
        public string SOURCE_SUBINVENTORY { get; set; }
    	[DataMember]
        public Nullable<decimal> SOURCE_ORGANIZATION_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> REQUISITION_APPROVAL_TYPE { get; set; }
    	[DataMember]
        public Nullable<decimal> EXPENSE_ACCOUNT { get; set; }
    	[DataMember]
        public Nullable<decimal> ENCUMBRANCE_ACCOUNT { get; set; }
    	[DataMember]
        public string ATTRIBUTE_CATEGORY { get; set; }
    	[DataMember]
        public string ATTRIBUTE1 { get; set; }
    	[DataMember]
        public string ATTRIBUTE2 { get; set; }
    	[DataMember]
        public string ATTRIBUTE3 { get; set; }
    	[DataMember]
        public string ATTRIBUTE4 { get; set; }
    	[DataMember]
        public string ATTRIBUTE5 { get; set; }
    	[DataMember]
        public string ATTRIBUTE6 { get; set; }
    	[DataMember]
        public string ATTRIBUTE7 { get; set; }
    	[DataMember]
        public string ATTRIBUTE8 { get; set; }
    	[DataMember]
        public string ATTRIBUTE9 { get; set; }
    	[DataMember]
        public string ATTRIBUTE10 { get; set; }
    	[DataMember]
        public string ATTRIBUTE11 { get; set; }
    	[DataMember]
        public string ATTRIBUTE12 { get; set; }
    	[DataMember]
        public string ATTRIBUTE13 { get; set; }
    	[DataMember]
        public string ATTRIBUTE14 { get; set; }
    	[DataMember]
        public string ATTRIBUTE15 { get; set; }
    	[DataMember]
        public Nullable<decimal> REQUEST_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> PROGRAM_APPLICATION_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> PROGRAM_ID { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> PROGRAM_UPDATE_DATE { get; set; }
    	[DataMember]
        public Nullable<decimal> PREPROCESSING_LEAD_TIME { get; set; }
    	[DataMember]
        public Nullable<decimal> PROCESSING_LEAD_TIME { get; set; }
    	[DataMember]
        public Nullable<decimal> POSTPROCESSING_LEAD_TIME { get; set; }
    	[DataMember]
        public string DEMAND_CLASS { get; set; }
    	[DataMember]
        public Nullable<long> PROJECT_ID { get; set; }
    	[DataMember]
        public Nullable<long> TASK_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> SUBINVENTORY_USAGE { get; set; }
    	[DataMember]
        public Nullable<decimal> NOTIFY_LIST_ID { get; set; }
    	[DataMember]
        public string PICK_UOM_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> DEPRECIABLE_FLAG { get; set; }
    	[DataMember]
        public Nullable<long> LOCATION_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> DEFAULT_COST_GROUP_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> STATUS_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> DEFAULT_LOC_STATUS_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> LPN_CONTROLLED_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> PICK_METHODOLOGY { get; set; }
    	[DataMember]
        public Nullable<decimal> CARTONIZATION_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> DROPPING_ORDER { get; set; }
    	[DataMember]
        public Nullable<decimal> SUBINVENTORY_TYPE { get; set; }
    	[DataMember]
        public Nullable<decimal> PLANNING_LEVEL { get; set; }
    	[DataMember]
        public Nullable<decimal> DEFAULT_COUNT_TYPE_CODE { get; set; }
    	[DataMember]
        public string ENABLE_BULK_PICK { get; set; }
    	[DataMember]
        public string ENABLE_LOCATOR_ALIAS { get; set; }
    	[DataMember]
        public string ENFORCE_ALIAS_UNIQUENESS { get; set; }
    	[DataMember]
        public string ENABLE_OPP_CYC_COUNT { get; set; }
    	[DataMember]
        public Nullable<short> OPP_CYC_COUNT_DAYS { get; set; }
    	[DataMember]
        public Nullable<decimal> OPP_CYC_COUNT_HEADER_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> OPP_CYC_COUNT_QUANTITY { get; set; }
    }
}
