//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.WCFModel
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class EBS_MTL_SYSTEM_ITEMS_B
    {
    	[DataMember]
        public decimal INVENTORY_ITEM_ID { get; set; }
    	[DataMember]
        public decimal ORGANIZATION_ID { get; set; }
    	[DataMember]
        public System.DateTime LAST_UPDATE_DATE { get; set; }
    	[DataMember]
        public decimal LAST_UPDATED_BY { get; set; }
    	[DataMember]
        public System.DateTime CREATION_DATE { get; set; }
    	[DataMember]
        public decimal CREATED_BY { get; set; }
    	[DataMember]
        public Nullable<decimal> LAST_UPDATE_LOGIN { get; set; }
    	[DataMember]
        public string SUMMARY_FLAG { get; set; }
    	[DataMember]
        public string ENABLED_FLAG { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> START_DATE_ACTIVE { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> END_DATE_ACTIVE { get; set; }
    	[DataMember]
        public string DESCRIPTION { get; set; }
    	[DataMember]
        public Nullable<int> BUYER_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> ACCOUNTING_RULE_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> INVOICING_RULE_ID { get; set; }
    	[DataMember]
        public string SEGMENT1 { get; set; }
    	[DataMember]
        public string SEGMENT2 { get; set; }
    	[DataMember]
        public string SEGMENT3 { get; set; }
    	[DataMember]
        public string SEGMENT4 { get; set; }
    	[DataMember]
        public string SEGMENT5 { get; set; }
    	[DataMember]
        public string SEGMENT6 { get; set; }
    	[DataMember]
        public string SEGMENT7 { get; set; }
    	[DataMember]
        public string SEGMENT8 { get; set; }
    	[DataMember]
        public string SEGMENT9 { get; set; }
    	[DataMember]
        public string SEGMENT10 { get; set; }
    	[DataMember]
        public string SEGMENT11 { get; set; }
    	[DataMember]
        public string SEGMENT12 { get; set; }
    	[DataMember]
        public string SEGMENT13 { get; set; }
    	[DataMember]
        public string SEGMENT14 { get; set; }
    	[DataMember]
        public string SEGMENT15 { get; set; }
    	[DataMember]
        public string SEGMENT16 { get; set; }
    	[DataMember]
        public string SEGMENT17 { get; set; }
    	[DataMember]
        public string SEGMENT18 { get; set; }
    	[DataMember]
        public string SEGMENT19 { get; set; }
    	[DataMember]
        public string SEGMENT20 { get; set; }
    	[DataMember]
        public string ATTRIBUTE_CATEGORY { get; set; }
    	[DataMember]
        public string ATTRIBUTE1 { get; set; }
    	[DataMember]
        public string ATTRIBUTE2 { get; set; }
    	[DataMember]
        public string ATTRIBUTE3 { get; set; }
    	[DataMember]
        public string ATTRIBUTE4 { get; set; }
    	[DataMember]
        public string ATTRIBUTE5 { get; set; }
    	[DataMember]
        public string ATTRIBUTE6 { get; set; }
    	[DataMember]
        public string ATTRIBUTE7 { get; set; }
    	[DataMember]
        public string ATTRIBUTE8 { get; set; }
    	[DataMember]
        public string ATTRIBUTE9 { get; set; }
    	[DataMember]
        public string ATTRIBUTE10 { get; set; }
    	[DataMember]
        public string ATTRIBUTE11 { get; set; }
    	[DataMember]
        public string ATTRIBUTE12 { get; set; }
    	[DataMember]
        public string ATTRIBUTE13 { get; set; }
    	[DataMember]
        public string ATTRIBUTE14 { get; set; }
    	[DataMember]
        public string ATTRIBUTE15 { get; set; }
    	[DataMember]
        public string PURCHASING_ITEM_FLAG { get; set; }
    	[DataMember]
        public string SHIPPABLE_ITEM_FLAG { get; set; }
    	[DataMember]
        public string CUSTOMER_ORDER_FLAG { get; set; }
    	[DataMember]
        public string INTERNAL_ORDER_FLAG { get; set; }
    	[DataMember]
        public string SERVICE_ITEM_FLAG { get; set; }
    	[DataMember]
        public string INVENTORY_ITEM_FLAG { get; set; }
    	[DataMember]
        public string ENG_ITEM_FLAG { get; set; }
    	[DataMember]
        public string INVENTORY_ASSET_FLAG { get; set; }
    	[DataMember]
        public string PURCHASING_ENABLED_FLAG { get; set; }
    	[DataMember]
        public string CUSTOMER_ORDER_ENABLED_FLAG { get; set; }
    	[DataMember]
        public string INTERNAL_ORDER_ENABLED_FLAG { get; set; }
    	[DataMember]
        public string SO_TRANSACTIONS_FLAG { get; set; }
    	[DataMember]
        public string MTL_TRANSACTIONS_ENABLED_FLAG { get; set; }
    	[DataMember]
        public string STOCK_ENABLED_FLAG { get; set; }
    	[DataMember]
        public string BOM_ENABLED_FLAG { get; set; }
    	[DataMember]
        public string BUILD_IN_WIP_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> REVISION_QTY_CONTROL_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> ITEM_CATALOG_GROUP_ID { get; set; }
    	[DataMember]
        public string CATALOG_STATUS_FLAG { get; set; }
    	[DataMember]
        public string RETURNABLE_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> DEFAULT_SHIPPING_ORG { get; set; }
    	[DataMember]
        public string COLLATERAL_FLAG { get; set; }
    	[DataMember]
        public string TAXABLE_FLAG { get; set; }
    	[DataMember]
        public string QTY_RCV_EXCEPTION_CODE { get; set; }
    	[DataMember]
        public string ALLOW_ITEM_DESC_UPDATE_FLAG { get; set; }
    	[DataMember]
        public string INSPECTION_REQUIRED_FLAG { get; set; }
    	[DataMember]
        public string RECEIPT_REQUIRED_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> MARKET_PRICE { get; set; }
    	[DataMember]
        public Nullable<decimal> HAZARD_CLASS_ID { get; set; }
    	[DataMember]
        public string RFQ_REQUIRED_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> QTY_RCV_TOLERANCE { get; set; }
    	[DataMember]
        public Nullable<decimal> LIST_PRICE_PER_UNIT { get; set; }
    	[DataMember]
        public Nullable<decimal> UN_NUMBER_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> PRICE_TOLERANCE_PERCENT { get; set; }
    	[DataMember]
        public Nullable<decimal> ASSET_CATEGORY_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> ROUNDING_FACTOR { get; set; }
    	[DataMember]
        public string UNIT_OF_ISSUE { get; set; }
    	[DataMember]
        public string ENFORCE_SHIP_TO_LOCATION_CODE { get; set; }
    	[DataMember]
        public string ALLOW_SUBSTITUTE_RECEIPTS_FLAG { get; set; }
    	[DataMember]
        public string ALLOW_UNORDERED_RECEIPTS_FLAG { get; set; }
    	[DataMember]
        public string ALLOW_EXPRESS_DELIVERY_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> DAYS_EARLY_RECEIPT_ALLOWED { get; set; }
    	[DataMember]
        public Nullable<decimal> DAYS_LATE_RECEIPT_ALLOWED { get; set; }
    	[DataMember]
        public string RECEIPT_DAYS_EXCEPTION_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> RECEIVING_ROUTING_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> INVOICE_CLOSE_TOLERANCE { get; set; }
    	[DataMember]
        public Nullable<decimal> RECEIVE_CLOSE_TOLERANCE { get; set; }
    	[DataMember]
        public string AUTO_LOT_ALPHA_PREFIX { get; set; }
    	[DataMember]
        public string START_AUTO_LOT_NUMBER { get; set; }
    	[DataMember]
        public Nullable<decimal> LOT_CONTROL_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> SHELF_LIFE_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> SHELF_LIFE_DAYS { get; set; }
    	[DataMember]
        public Nullable<decimal> SERIAL_NUMBER_CONTROL_CODE { get; set; }
    	[DataMember]
        public string START_AUTO_SERIAL_NUMBER { get; set; }
    	[DataMember]
        public string AUTO_SERIAL_ALPHA_PREFIX { get; set; }
    	[DataMember]
        public Nullable<decimal> SOURCE_TYPE { get; set; }
    	[DataMember]
        public Nullable<decimal> SOURCE_ORGANIZATION_ID { get; set; }
    	[DataMember]
        public string SOURCE_SUBINVENTORY { get; set; }
    	[DataMember]
        public Nullable<decimal> EXPENSE_ACCOUNT { get; set; }
    	[DataMember]
        public Nullable<decimal> ENCUMBRANCE_ACCOUNT { get; set; }
    	[DataMember]
        public Nullable<decimal> RESTRICT_SUBINVENTORIES_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> UNIT_WEIGHT { get; set; }
    	[DataMember]
        public string WEIGHT_UOM_CODE { get; set; }
    	[DataMember]
        public string VOLUME_UOM_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> UNIT_VOLUME { get; set; }
    	[DataMember]
        public Nullable<decimal> RESTRICT_LOCATORS_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> LOCATION_CONTROL_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> SHRINKAGE_RATE { get; set; }
    	[DataMember]
        public Nullable<decimal> ACCEPTABLE_EARLY_DAYS { get; set; }
    	[DataMember]
        public Nullable<decimal> PLANNING_TIME_FENCE_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> DEMAND_TIME_FENCE_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> LEAD_TIME_LOT_SIZE { get; set; }
    	[DataMember]
        public Nullable<decimal> STD_LOT_SIZE { get; set; }
    	[DataMember]
        public Nullable<decimal> CUM_MANUFACTURING_LEAD_TIME { get; set; }
    	[DataMember]
        public Nullable<decimal> OVERRUN_PERCENTAGE { get; set; }
    	[DataMember]
        public string MRP_CALCULATE_ATP_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> ACCEPTABLE_RATE_INCREASE { get; set; }
    	[DataMember]
        public Nullable<decimal> ACCEPTABLE_RATE_DECREASE { get; set; }
    	[DataMember]
        public Nullable<decimal> CUMULATIVE_TOTAL_LEAD_TIME { get; set; }
    	[DataMember]
        public Nullable<decimal> PLANNING_TIME_FENCE_DAYS { get; set; }
    	[DataMember]
        public Nullable<decimal> DEMAND_TIME_FENCE_DAYS { get; set; }
    	[DataMember]
        public string END_ASSEMBLY_PEGGING_FLAG { get; set; }
    	[DataMember]
        public string REPETITIVE_PLANNING_FLAG { get; set; }
    	[DataMember]
        public string PLANNING_EXCEPTION_SET { get; set; }
    	[DataMember]
        public decimal BOM_ITEM_TYPE { get; set; }
    	[DataMember]
        public string PICK_COMPONENTS_FLAG { get; set; }
    	[DataMember]
        public string REPLENISH_TO_ORDER_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> BASE_ITEM_ID { get; set; }
    	[DataMember]
        public string ATP_COMPONENTS_FLAG { get; set; }
    	[DataMember]
        public string ATP_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> FIXED_LEAD_TIME { get; set; }
    	[DataMember]
        public Nullable<decimal> VARIABLE_LEAD_TIME { get; set; }
    	[DataMember]
        public Nullable<decimal> WIP_SUPPLY_LOCATOR_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> WIP_SUPPLY_TYPE { get; set; }
    	[DataMember]
        public string WIP_SUPPLY_SUBINVENTORY { get; set; }
    	[DataMember]
        public string PRIMARY_UOM_CODE { get; set; }
    	[DataMember]
        public string PRIMARY_UNIT_OF_MEASURE { get; set; }
    	[DataMember]
        public Nullable<decimal> ALLOWED_UNITS_LOOKUP_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> COST_OF_SALES_ACCOUNT { get; set; }
    	[DataMember]
        public Nullable<decimal> SALES_ACCOUNT { get; set; }
    	[DataMember]
        public string DEFAULT_INCLUDE_IN_ROLLUP_FLAG { get; set; }
    	[DataMember]
        public string INVENTORY_ITEM_STATUS_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> INVENTORY_PLANNING_CODE { get; set; }
    	[DataMember]
        public string PLANNER_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> PLANNING_MAKE_BUY_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> FIXED_LOT_MULTIPLIER { get; set; }
    	[DataMember]
        public Nullable<decimal> ROUNDING_CONTROL_TYPE { get; set; }
    	[DataMember]
        public Nullable<decimal> CARRYING_COST { get; set; }
    	[DataMember]
        public Nullable<decimal> POSTPROCESSING_LEAD_TIME { get; set; }
    	[DataMember]
        public Nullable<decimal> PREPROCESSING_LEAD_TIME { get; set; }
    	[DataMember]
        public Nullable<decimal> FULL_LEAD_TIME { get; set; }
    	[DataMember]
        public Nullable<decimal> ORDER_COST { get; set; }
    	[DataMember]
        public Nullable<decimal> MRP_SAFETY_STOCK_PERCENT { get; set; }
    	[DataMember]
        public Nullable<decimal> MRP_SAFETY_STOCK_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> MIN_MINMAX_QUANTITY { get; set; }
    	[DataMember]
        public Nullable<decimal> MAX_MINMAX_QUANTITY { get; set; }
    	[DataMember]
        public Nullable<decimal> MINIMUM_ORDER_QUANTITY { get; set; }
    	[DataMember]
        public Nullable<decimal> FIXED_ORDER_QUANTITY { get; set; }
    	[DataMember]
        public Nullable<decimal> FIXED_DAYS_SUPPLY { get; set; }
    	[DataMember]
        public Nullable<decimal> MAXIMUM_ORDER_QUANTITY { get; set; }
    	[DataMember]
        public Nullable<decimal> ATP_RULE_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> PICKING_RULE_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> RESERVABLE_TYPE { get; set; }
    	[DataMember]
        public Nullable<decimal> POSITIVE_MEASUREMENT_ERROR { get; set; }
    	[DataMember]
        public Nullable<decimal> NEGATIVE_MEASUREMENT_ERROR { get; set; }
    	[DataMember]
        public string ENGINEERING_ECN_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> ENGINEERING_ITEM_ID { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> ENGINEERING_DATE { get; set; }
    	[DataMember]
        public Nullable<decimal> SERVICE_STARTING_DELAY { get; set; }
    	[DataMember]
        public string VENDOR_WARRANTY_FLAG { get; set; }
    	[DataMember]
        public string SERVICEABLE_COMPONENT_FLAG { get; set; }
    	[DataMember]
        public string SERVICEABLE_PRODUCT_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> BASE_WARRANTY_SERVICE_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> PAYMENT_TERMS_ID { get; set; }
    	[DataMember]
        public string PREVENTIVE_MAINTENANCE_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> PRIMARY_SPECIALIST_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> SECONDARY_SPECIALIST_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> SERVICEABLE_ITEM_CLASS_ID { get; set; }
    	[DataMember]
        public string TIME_BILLABLE_FLAG { get; set; }
    	[DataMember]
        public string MATERIAL_BILLABLE_FLAG { get; set; }
    	[DataMember]
        public string EXPENSE_BILLABLE_FLAG { get; set; }
    	[DataMember]
        public string PRORATE_SERVICE_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> COVERAGE_SCHEDULE_ID { get; set; }
    	[DataMember]
        public string SERVICE_DURATION_PERIOD_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> SERVICE_DURATION { get; set; }
    	[DataMember]
        public Nullable<decimal> WARRANTY_VENDOR_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> MAX_WARRANTY_AMOUNT { get; set; }
    	[DataMember]
        public string RESPONSE_TIME_PERIOD_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> RESPONSE_TIME_VALUE { get; set; }
    	[DataMember]
        public string NEW_REVISION_CODE { get; set; }
    	[DataMember]
        public string INVOICEABLE_ITEM_FLAG { get; set; }
    	[DataMember]
        public string TAX_CODE { get; set; }
    	[DataMember]
        public string INVOICE_ENABLED_FLAG { get; set; }
    	[DataMember]
        public string MUST_USE_APPROVED_VENDOR_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> REQUEST_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> PROGRAM_APPLICATION_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> PROGRAM_ID { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> PROGRAM_UPDATE_DATE { get; set; }
    	[DataMember]
        public string OUTSIDE_OPERATION_FLAG { get; set; }
    	[DataMember]
        public string OUTSIDE_OPERATION_UOM_TYPE { get; set; }
    	[DataMember]
        public Nullable<decimal> SAFETY_STOCK_BUCKET_DAYS { get; set; }
    	[DataMember]
        public Nullable<decimal> AUTO_REDUCE_MPS { get; set; }
    	[DataMember]
        public string COSTING_ENABLED_FLAG { get; set; }
    	[DataMember]
        public string AUTO_CREATED_CONFIG_FLAG { get; set; }
    	[DataMember]
        public string CYCLE_COUNT_ENABLED_FLAG { get; set; }
    	[DataMember]
        public string ITEM_TYPE { get; set; }
    	[DataMember]
        public string MODEL_CONFIG_CLAUSE_NAME { get; set; }
    	[DataMember]
        public string SHIP_MODEL_COMPLETE_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> MRP_PLANNING_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> RETURN_INSPECTION_REQUIREMENT { get; set; }
    	[DataMember]
        public Nullable<decimal> ATO_FORECAST_CONTROL { get; set; }
    	[DataMember]
        public Nullable<decimal> RELEASE_TIME_FENCE_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> RELEASE_TIME_FENCE_DAYS { get; set; }
    	[DataMember]
        public string CONTAINER_ITEM_FLAG { get; set; }
    	[DataMember]
        public string VEHICLE_ITEM_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> MAXIMUM_LOAD_WEIGHT { get; set; }
    	[DataMember]
        public Nullable<decimal> MINIMUM_FILL_PERCENT { get; set; }
    	[DataMember]
        public string CONTAINER_TYPE_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> INTERNAL_VOLUME { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> WH_UPDATE_DATE { get; set; }
    	[DataMember]
        public Nullable<decimal> PRODUCT_FAMILY_ITEM_ID { get; set; }
    	[DataMember]
        public string GLOBAL_ATTRIBUTE_CATEGORY { get; set; }
    	[DataMember]
        public string GLOBAL_ATTRIBUTE1 { get; set; }
    	[DataMember]
        public string GLOBAL_ATTRIBUTE2 { get; set; }
    	[DataMember]
        public string GLOBAL_ATTRIBUTE3 { get; set; }
    	[DataMember]
        public string GLOBAL_ATTRIBUTE4 { get; set; }
    	[DataMember]
        public string GLOBAL_ATTRIBUTE5 { get; set; }
    	[DataMember]
        public string GLOBAL_ATTRIBUTE6 { get; set; }
    	[DataMember]
        public string GLOBAL_ATTRIBUTE7 { get; set; }
    	[DataMember]
        public string GLOBAL_ATTRIBUTE8 { get; set; }
    	[DataMember]
        public string GLOBAL_ATTRIBUTE9 { get; set; }
    	[DataMember]
        public string GLOBAL_ATTRIBUTE10 { get; set; }
    	[DataMember]
        public string PURCHASING_TAX_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> OVERCOMPLETION_TOLERANCE_TYPE { get; set; }
    	[DataMember]
        public Nullable<decimal> OVERCOMPLETION_TOLERANCE_VALUE { get; set; }
    	[DataMember]
        public Nullable<decimal> EFFECTIVITY_CONTROL { get; set; }
    	[DataMember]
        public string CHECK_SHORTAGES_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> OVER_SHIPMENT_TOLERANCE { get; set; }
    	[DataMember]
        public Nullable<decimal> UNDER_SHIPMENT_TOLERANCE { get; set; }
    	[DataMember]
        public Nullable<decimal> OVER_RETURN_TOLERANCE { get; set; }
    	[DataMember]
        public Nullable<decimal> UNDER_RETURN_TOLERANCE { get; set; }
    	[DataMember]
        public Nullable<decimal> EQUIPMENT_TYPE { get; set; }
    	[DataMember]
        public string RECOVERED_PART_DISP_CODE { get; set; }
    	[DataMember]
        public string DEFECT_TRACKING_ON_FLAG { get; set; }
    	[DataMember]
        public string USAGE_ITEM_FLAG { get; set; }
    	[DataMember]
        public string EVENT_FLAG { get; set; }
    	[DataMember]
        public string ELECTRONIC_FLAG { get; set; }
    	[DataMember]
        public string DOWNLOADABLE_FLAG { get; set; }
    	[DataMember]
        public string VOL_DISCOUNT_EXEMPT_FLAG { get; set; }
    	[DataMember]
        public string COUPON_EXEMPT_FLAG { get; set; }
    	[DataMember]
        public string COMMS_NL_TRACKABLE_FLAG { get; set; }
    	[DataMember]
        public string ASSET_CREATION_CODE { get; set; }
    	[DataMember]
        public string COMMS_ACTIVATION_REQD_FLAG { get; set; }
    	[DataMember]
        public string ORDERABLE_ON_WEB_FLAG { get; set; }
    	[DataMember]
        public string BACK_ORDERABLE_FLAG { get; set; }
    	[DataMember]
        public string WEB_STATUS { get; set; }
    	[DataMember]
        public string INDIVISIBLE_FLAG { get; set; }
    	[DataMember]
        public string DIMENSION_UOM_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> UNIT_LENGTH { get; set; }
    	[DataMember]
        public Nullable<decimal> UNIT_WIDTH { get; set; }
    	[DataMember]
        public Nullable<decimal> UNIT_HEIGHT { get; set; }
    	[DataMember]
        public string BULK_PICKED_FLAG { get; set; }
    	[DataMember]
        public string LOT_STATUS_ENABLED { get; set; }
    	[DataMember]
        public Nullable<decimal> DEFAULT_LOT_STATUS_ID { get; set; }
    	[DataMember]
        public string SERIAL_STATUS_ENABLED { get; set; }
    	[DataMember]
        public Nullable<decimal> DEFAULT_SERIAL_STATUS_ID { get; set; }
    	[DataMember]
        public string LOT_SPLIT_ENABLED { get; set; }
    	[DataMember]
        public string LOT_MERGE_ENABLED { get; set; }
    	[DataMember]
        public Nullable<decimal> INVENTORY_CARRY_PENALTY { get; set; }
    	[DataMember]
        public Nullable<decimal> OPERATION_SLACK_PENALTY { get; set; }
    	[DataMember]
        public string FINANCING_ALLOWED_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> EAM_ITEM_TYPE { get; set; }
    	[DataMember]
        public string EAM_ACTIVITY_TYPE_CODE { get; set; }
    	[DataMember]
        public string EAM_ACTIVITY_CAUSE_CODE { get; set; }
    	[DataMember]
        public string EAM_ACT_NOTIFICATION_FLAG { get; set; }
    	[DataMember]
        public string EAM_ACT_SHUTDOWN_STATUS { get; set; }
    	[DataMember]
        public Nullable<decimal> DUAL_UOM_CONTROL { get; set; }
    	[DataMember]
        public string SECONDARY_UOM_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> DUAL_UOM_DEVIATION_HIGH { get; set; }
    	[DataMember]
        public Nullable<decimal> DUAL_UOM_DEVIATION_LOW { get; set; }
    	[DataMember]
        public string CONTRACT_ITEM_TYPE_CODE { get; set; }
    	[DataMember]
        public string SUBSCRIPTION_DEPEND_FLAG { get; set; }
    	[DataMember]
        public string SERV_REQ_ENABLED_CODE { get; set; }
    	[DataMember]
        public string SERV_BILLING_ENABLED_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> SERV_IMPORTANCE_LEVEL { get; set; }
    	[DataMember]
        public string PLANNED_INV_POINT_FLAG { get; set; }
    	[DataMember]
        public string LOT_TRANSLATE_ENABLED { get; set; }
    	[DataMember]
        public string DEFAULT_SO_SOURCE_TYPE { get; set; }
    	[DataMember]
        public string CREATE_SUPPLY_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> SUBSTITUTION_WINDOW_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> SUBSTITUTION_WINDOW_DAYS { get; set; }
    	[DataMember]
        public string IB_ITEM_INSTANCE_CLASS { get; set; }
    	[DataMember]
        public string CONFIG_MODEL_TYPE { get; set; }
    	[DataMember]
        public string LOT_SUBSTITUTION_ENABLED { get; set; }
    	[DataMember]
        public Nullable<decimal> MINIMUM_LICENSE_QUANTITY { get; set; }
    	[DataMember]
        public string EAM_ACTIVITY_SOURCE_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> LIFECYCLE_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> CURRENT_PHASE_ID { get; set; }
    	[DataMember]
        public Nullable<int> OBJECT_VERSION_NUMBER { get; set; }
    	[DataMember]
        public string TRACKING_QUANTITY_IND { get; set; }
    	[DataMember]
        public string ONT_PRICING_QTY_SOURCE { get; set; }
    	[DataMember]
        public string SECONDARY_DEFAULT_IND { get; set; }
    	[DataMember]
        public Nullable<decimal> OPTION_SPECIFIC_SOURCED { get; set; }
    	[DataMember]
        public string APPROVAL_STATUS { get; set; }
    	[DataMember]
        public Nullable<decimal> VMI_MINIMUM_UNITS { get; set; }
    	[DataMember]
        public Nullable<decimal> VMI_MINIMUM_DAYS { get; set; }
    	[DataMember]
        public Nullable<decimal> VMI_MAXIMUM_UNITS { get; set; }
    	[DataMember]
        public Nullable<decimal> VMI_MAXIMUM_DAYS { get; set; }
    	[DataMember]
        public Nullable<decimal> VMI_FIXED_ORDER_QUANTITY { get; set; }
    	[DataMember]
        public Nullable<decimal> SO_AUTHORIZATION_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> CONSIGNED_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> ASN_AUTOEXPIRE_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> VMI_FORECAST_TYPE { get; set; }
    	[DataMember]
        public Nullable<decimal> FORECAST_HORIZON { get; set; }
    	[DataMember]
        public Nullable<decimal> EXCLUDE_FROM_BUDGET_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> DAYS_TGT_INV_SUPPLY { get; set; }
    	[DataMember]
        public Nullable<decimal> DAYS_TGT_INV_WINDOW { get; set; }
    	[DataMember]
        public Nullable<decimal> DAYS_MAX_INV_SUPPLY { get; set; }
    	[DataMember]
        public Nullable<decimal> DAYS_MAX_INV_WINDOW { get; set; }
    	[DataMember]
        public Nullable<decimal> DRP_PLANNED_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> CRITICAL_COMPONENT_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> CONTINOUS_TRANSFER { get; set; }
    	[DataMember]
        public Nullable<decimal> CONVERGENCE { get; set; }
    	[DataMember]
        public Nullable<decimal> DIVERGENCE { get; set; }
    	[DataMember]
        public string CONFIG_ORGS { get; set; }
    	[DataMember]
        public string CONFIG_MATCH { get; set; }
    	[DataMember]
        public string ATTRIBUTE16 { get; set; }
    	[DataMember]
        public string ATTRIBUTE17 { get; set; }
    	[DataMember]
        public string ATTRIBUTE18 { get; set; }
    	[DataMember]
        public string ATTRIBUTE19 { get; set; }
    	[DataMember]
        public string ATTRIBUTE20 { get; set; }
    	[DataMember]
        public string ATTRIBUTE21 { get; set; }
    	[DataMember]
        public string ATTRIBUTE22 { get; set; }
    	[DataMember]
        public string ATTRIBUTE23 { get; set; }
    	[DataMember]
        public string ATTRIBUTE24 { get; set; }
    	[DataMember]
        public string ATTRIBUTE25 { get; set; }
    	[DataMember]
        public string ATTRIBUTE26 { get; set; }
    	[DataMember]
        public string ATTRIBUTE27 { get; set; }
    	[DataMember]
        public string ATTRIBUTE28 { get; set; }
    	[DataMember]
        public string ATTRIBUTE29 { get; set; }
    	[DataMember]
        public string ATTRIBUTE30 { get; set; }
    	[DataMember]
        public string CAS_NUMBER { get; set; }
    	[DataMember]
        public string CHILD_LOT_FLAG { get; set; }
    	[DataMember]
        public string CHILD_LOT_PREFIX { get; set; }
    	[DataMember]
        public Nullable<decimal> CHILD_LOT_STARTING_NUMBER { get; set; }
    	[DataMember]
        public string CHILD_LOT_VALIDATION_FLAG { get; set; }
    	[DataMember]
        public string COPY_LOT_ATTRIBUTE_FLAG { get; set; }
    	[DataMember]
        public string DEFAULT_GRADE { get; set; }
    	[DataMember]
        public string EXPIRATION_ACTION_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> EXPIRATION_ACTION_INTERVAL { get; set; }
    	[DataMember]
        public string GRADE_CONTROL_FLAG { get; set; }
    	[DataMember]
        public string HAZARDOUS_MATERIAL_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> HOLD_DAYS { get; set; }
    	[DataMember]
        public string LOT_DIVISIBLE_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> MATURITY_DAYS { get; set; }
    	[DataMember]
        public string PARENT_CHILD_GENERATION_FLAG { get; set; }
    	[DataMember]
        public string PROCESS_COSTING_ENABLED_FLAG { get; set; }
    	[DataMember]
        public string PROCESS_EXECUTION_ENABLED_FLAG { get; set; }
    	[DataMember]
        public string PROCESS_QUALITY_ENABLED_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> PROCESS_SUPPLY_LOCATOR_ID { get; set; }
    	[DataMember]
        public string PROCESS_SUPPLY_SUBINVENTORY { get; set; }
    	[DataMember]
        public Nullable<decimal> PROCESS_YIELD_LOCATOR_ID { get; set; }
    	[DataMember]
        public string PROCESS_YIELD_SUBINVENTORY { get; set; }
    	[DataMember]
        public string RECIPE_ENABLED_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> RETEST_INTERVAL { get; set; }
    	[DataMember]
        public string CHARGE_PERIODICITY_CODE { get; set; }
    	[DataMember]
        public Nullable<decimal> REPAIR_LEADTIME { get; set; }
    	[DataMember]
        public Nullable<decimal> REPAIR_YIELD { get; set; }
    	[DataMember]
        public string PREPOSITION_POINT { get; set; }
    	[DataMember]
        public Nullable<decimal> REPAIR_PROGRAM { get; set; }
    	[DataMember]
        public Nullable<decimal> SUBCONTRACTING_COMPONENT { get; set; }
    	[DataMember]
        public Nullable<decimal> OUTSOURCED_ASSEMBLY { get; set; }
    	[DataMember]
        public string EGO_MASTER_ITEMS_DFF_CTX { get; set; }
    	[DataMember]
        public string GDSN_OUTBOUND_ENABLED_FLAG { get; set; }
    	[DataMember]
        public string TRADE_ITEM_DESCRIPTOR { get; set; }
    	[DataMember]
        public Nullable<decimal> STYLE_ITEM_ID { get; set; }
    	[DataMember]
        public string STYLE_ITEM_FLAG { get; set; }
    	[DataMember]
        public Nullable<decimal> LAST_SUBMITTED_NIR_ID { get; set; }
    	[DataMember]
        public Nullable<decimal> DEFAULT_MATERIAL_STATUS_ID { get; set; }
    	[DataMember]
        public string GLOBAL_ATTRIBUTE11 { get; set; }
    	[DataMember]
        public string GLOBAL_ATTRIBUTE12 { get; set; }
    	[DataMember]
        public string GLOBAL_ATTRIBUTE13 { get; set; }
    	[DataMember]
        public string GLOBAL_ATTRIBUTE14 { get; set; }
    	[DataMember]
        public string GLOBAL_ATTRIBUTE15 { get; set; }
    	[DataMember]
        public string GLOBAL_ATTRIBUTE16 { get; set; }
    	[DataMember]
        public string GLOBAL_ATTRIBUTE17 { get; set; }
    	[DataMember]
        public string GLOBAL_ATTRIBUTE18 { get; set; }
    	[DataMember]
        public string GLOBAL_ATTRIBUTE19 { get; set; }
    	[DataMember]
        public string GLOBAL_ATTRIBUTE20 { get; set; }
    }
}
