//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.WCFModel
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class WMS_UOM
    {
    	[DataMember]
        public decimal UOM_ID { get; set; }
    	[DataMember]
        public string UOM_CODE { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> START_DATE { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> END_DATE { get; set; }
    }
}
